#!/bin/bash
#
# ed3-folder
# By: Brian Carter
# robotmachine@gmail.com
#
# Writes id3 tags.
#
## Dependencies.
# * eyeD3 <http://eyed3.nicfit.net>
#
# This script expects all artists to be contained within their own directory.
# ie. /home/robot/Music/Artist
#
# Within each folder should be a new directory per album with the release year prepended.
# ie. /home/robot/Music/Artist/1978 Album Title
#
# Each album should contain files prepended with a two digit track number and the title of the track.
# ie. /home/robot/Music/Artist/1978 Album Title/01 First Track.mp3
# An _ will be converted to a / and a ¿ will be converted to ?
#
# In the event of a multi-disc set, the format would be:
# 01-01 First Track of First Disc.mp3
# 02-03 Third Track of Second Disc.mp3
#
# Within each artist folder a file named .genre.txt containing a single line for a genre will be used.
# If no such file is present, then a genre will be requested interactively.
# Alternatively, an argument can be passed to set the genre: $> ed3-folder "The Genre"
#
# Deletes id3 tags on all mp3 files in the current directory.
eyeD3 --remove-all *.mp3
#
# Run the script as id3-folder Genre. The genre will be set as that variable.
if [ -f ../.genre.txt ] ; then
eyeD3 --itunes --set-encoding=utf8 -G "$(cat ../.genre.txt)" *.mp3 ; 
else eyeD3 --itunes --set-encoding=utf8 -G "$@" *.mp3 ;
fi
#
# Uses the artist directory name to set artist name. 
# (See top of file for directory structure notes)
eyeD3 --itunes --set-encoding=utf8 -a "$(pwd | awk -F \/ '{ print $(NF-1) }')" *.mp3
#
# Takes out the year from the album directory and removes the year to set album title.
# (See top of file for directory structure notes)
eyeD3 --itunes --set-encoding=utf8 -A "$(pwd | awk -F \/ '{ print $NF }' | sed 's/.....\(.*\)/\1/' | sed 's@_@/@g' | sed 's/¿/?/g')" *.mp3
#
# Cuts the first four digits from the album directory for the year.
# Prefers .year.txt if it exists.
if [ -f .year.txt ] ; then
eyeD3 --itunes --set-encoding=utf8 -Y "$(cat .year.txt)" *.mp3 ;
else eyeD3 --itunes --set-encoding=utf8 -Y "$(pwd | awk -F \/ '{ print $NF }' | cut -c 1-4)" *.mp3
fi
#
# Figures out how many discs there are and make it assign tracks, number of discs, and track names accordingly.
# Works with up to ten discs.
if [ -f 10-01\ *.mp3 ] ; then
x="1" && z="$(ls -l 01-*.mp3 | wc -l | tr -d ' ')"; for y in 01-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 02-*.mp3 | wc -l | tr -d ' ')"; for y in 02-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 03-*.mp3 | wc -l | tr -d ' ')"; for y in 03-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 04-*.mp3 | wc -l | tr -d ' ')"; for y in 04-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 05-*.mp3 | wc -l | tr -d ' ')"; for y in 05-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 06-*.mp3 | wc -l | tr -d ' ')"; for y in 06-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 07-*.mp3 | wc -l | tr -d ' ')"; for y in 07-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 08-*.mp3 | wc -l | tr -d ' ')"; for y in 08-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 09-*.mp3 | wc -l | tr -d ' ')"; for y in 09-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 10-*.mp3 | wc -l | tr -d ' ')"; for y in 10-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
for x in 01-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "01"-D "10" "$x"; done
for x in 02-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "02"-D "10" "$x"; done
for x in 03-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "03"-D "10" "$x"; done
for x in 04-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "04"-D "10" "$x"; done
for x in 05-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "05"-D "10" "$x"; done
for x in 06-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "06"-D "10" "$x"; done
for x in 07-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "07"-D "10" "$x"; done
for x in 08-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "08"-D "10" "$x"; done
for x in 09-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "09"-D "10" "$x"; done
for x in 10-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "10"-D "10" "$x"; done
for x in *.mp3; do y=`echo $x | sed 's/......\(.*\)/\1/' | sed 's/.mp3//g' | sed 's/.mp3//g' | sed 's@_@/@g' | sed 's/¿/?/g'`; eyeD3 --itunes --set-encoding=utf8 -t "$y" "$x"; done
elif [ -f 09-01\ *.mp3 ]; then
x="1" && z="$(ls -l 01-*.mp3 | wc -l | tr -d ' ')"; for y in 01-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 02-*.mp3 | wc -l | tr -d ' ')"; for y in 02-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 03-*.mp3 | wc -l | tr -d ' ')"; for y in 03-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 04-*.mp3 | wc -l | tr -d ' ')"; for y in 04-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 05-*.mp3 | wc -l | tr -d ' ')"; for y in 05-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 06-*.mp3 | wc -l | tr -d ' ')"; for y in 06-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 07-*.mp3 | wc -l | tr -d ' ')"; for y in 07-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 08-*.mp3 | wc -l | tr -d ' ')"; for y in 08-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 09-*.mp3 | wc -l | tr -d ' ')"; for y in 09-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
for x in 01-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "01" -D "09" "$x"; done
for x in 02-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "02" -D "09" "$x"; done
for x in 03-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "03" -D "09" "$x"; done
for x in 04-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "04" -D "09" "$x"; done
for x in 05-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "05" -D "09" "$x"; done
for x in 06-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "06" -D "09" "$x"; done
for x in 07-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "07" -D "09" "$x"; done
for x in 08-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "08" -D "09" "$x"; done
for x in 09-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "09" -D "09" "$x"; done
for x in *.mp3; do y=`echo $x | sed 's/......\(.*\)/\1/' | sed 's/.mp3//g' | sed 's/.mp3//g' | sed 's@_@/@g' | sed 's/¿/?/g'`; eyeD3 --itunes --set-encoding=utf8 -t "$y" "$x"; done
elif [ -f 08-01\ *.mp3 ]; then
x="1" && z="$(ls -l 01-*.mp3 | wc -l | tr -d ' ')"; for y in 01-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 02-*.mp3 | wc -l | tr -d ' ')"; for y in 02-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 03-*.mp3 | wc -l | tr -d ' ')"; for y in 03-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 04-*.mp3 | wc -l | tr -d ' ')"; for y in 04-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 05-*.mp3 | wc -l | tr -d ' ')"; for y in 05-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 06-*.mp3 | wc -l | tr -d ' ')"; for y in 06-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 07-*.mp3 | wc -l | tr -d ' ')"; for y in 07-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 08-*.mp3 | wc -l | tr -d ' ')"; for y in 08-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
for x in 01-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "01" -D "08" "$x"; done
for x in 02-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "02" -D "08" "$x"; done
for x in 03-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "03" -D "08" "$x"; done
for x in 04-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "04" -D "08" "$x"; done
for x in 05-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "05" -D "08" "$x"; done
for x in 06-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "06" -D "08" "$x"; done
for x in 07-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "07" -D "08" "$x"; done
for x in 08-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "08" -D "08" "$x"; done
for x in *.mp3; do y=`echo $x | sed 's/......\(.*\)/\1/' | sed 's/.mp3//g' | sed 's/.mp3//g' | sed 's@_@/@g' | sed 's/¿/?/g'`; eyeD3 --itunes --set-encoding=utf8 -t "$y" "$x"; done
elif [ -f 07-01\ *.mp3 ]; then
x="1" && z="$(ls -l 01-*.mp3 | wc -l | tr -d ' ')"; for y in 01-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 02-*.mp3 | wc -l | tr -d ' ')"; for y in 02-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 03-*.mp3 | wc -l | tr -d ' ')"; for y in 03-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 04-*.mp3 | wc -l | tr -d ' ')"; for y in 04-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 05-*.mp3 | wc -l | tr -d ' ')"; for y in 05-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 06-*.mp3 | wc -l | tr -d ' ')"; for y in 06-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 07-*.mp3 | wc -l | tr -d ' ')"; for y in 07-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
for x in 01-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "01" -D "07" "$x"; done
for x in 02-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "02" -D "07" "$x"; done
for x in 03-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "03" -D "07" "$x"; done
for x in 04-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "04" -D "07" "$x"; done
for x in 05-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "05" -D "07" "$x"; done
for x in 06-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "06" -D "07" "$x"; done
for x in 07-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "07" -D "07" "$x"; done
for x in *.mp3; do y=`echo $x | sed 's/......\(.*\)/\1/' | sed 's/.mp3//g' | sed 's/.mp3//g' | sed 's@_@/@g' | sed 's/¿/?/g'`; eyeD3 --itunes --set-encoding=utf8 -t "$y" "$x"; done
elif [ -f 06-01\ *.mp3 ]; then
x="1" && z="$(ls -l 01-*.mp3 | wc -l | tr -d ' ')"; for y in 01-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 02-*.mp3 | wc -l | tr -d ' ')"; for y in 02-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 03-*.mp3 | wc -l | tr -d ' ')"; for y in 03-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 04-*.mp3 | wc -l | tr -d ' ')"; for y in 04-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 05-*.mp3 | wc -l | tr -d ' ')"; for y in 05-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 06-*.mp3 | wc -l | tr -d ' ')"; for y in 06-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
for x in 01-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "01" -D "06" "$x"; done
for x in 02-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "02" -D "06" "$x"; done
for x in 03-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "03" -D "06" "$x"; done
for x in 04-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "04" -D "06" "$x"; done
for x in 05-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "05" -D "06" "$x"; done
for x in 06-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "06" -D "06" "$x"; done
for x in *.mp3; do y=`echo $x | sed 's/......\(.*\)/\1/' | sed 's/.mp3//g' | sed 's/.mp3//g' | sed 's@_@/@g' | sed 's/¿/?/g'`; eyeD3 --itunes --set-encoding=utf8 -t "$y" "$x"; done
elif [ -f 05-01\ *.mp3 ]; then
x="1" && z="$(ls -l 01-*.mp3 | wc -l | tr -d ' ')"; for y in 01-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 02-*.mp3 | wc -l | tr -d ' ')"; for y in 02-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 03-*.mp3 | wc -l | tr -d ' ')"; for y in 03-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 04-*.mp3 | wc -l | tr -d ' ')"; for y in 04-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 05-*.mp3 | wc -l | tr -d ' ')"; for y in 05-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
for x in 01-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "01" -D "05" "$x"; done
for x in 02-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "02" -D "05" "$x"; done
for x in 03-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "03" -D "05" "$x"; done
for x in 04-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "04" -D "05" "$x"; done
for x in 05-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "05" -D "05" "$x"; done
for x in *.mp3; do y=`echo $x | sed 's/......\(.*\)/\1/' | sed 's/.mp3//g' | sed 's/.mp3//g' | sed 's@_@/@g' | sed 's/¿/?/g'`; eyeD3 --itunes --set-encoding=utf8 -t "$y" "$x"; done
elif [ -f 04-01\ *.mp3 ]; then
x="1" && z="$(ls -l 01-*.mp3 | wc -l | tr -d ' ')"; for y in 01-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 02-*.mp3 | wc -l | tr -d ' ')"; for y in 02-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 03-*.mp3 | wc -l | tr -d ' ')"; for y in 03-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 04-*.mp3 | wc -l | tr -d ' ')"; for y in 04-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
for x in 01-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "01" -D "04" "$x"; done
for x in 02-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "02" -D "04" "$x"; done
for x in 03-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "03" -D "04" "$x"; done
for x in 04-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "04" -D "04" "$x"; done
for x in *.mp3; do y=`echo $x | sed 's/......\(.*\)/\1/' | sed 's/.mp3//g' | sed 's/.mp3//g' | sed 's@_@/@g' | sed 's/¿/?/g'`; eyeD3 --itunes --set-encoding=utf8 -t "$y" "$x"; done
elif [ -f 03-01\ *.mp3 ]; then
x="1" && z="$(ls -l 01-*.mp3 | wc -l | tr -d ' ')"; for y in 01-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 02-*.mp3 | wc -l | tr -d ' ')"; for y in 02-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 03-*.mp3 | wc -l | tr -d ' ')"; for y in 03-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
for x in 01-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "01" -D "03" "$x"; done
for x in 02-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "02" -D "03" "$x"; done
for x in 03-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "03" -D "03" "$x"; done
for x in *.mp3; do y=`echo $x | sed 's/......\(.*\)/\1/' | sed 's/.mp3//g' | sed 's/.mp3//g' | sed 's@_@/@g' | sed 's/¿/?/g'`; eyeD3 --itunes --set-encoding=utf8 -t "$y" "$x"; done
elif [ -f 02-01\ *.mp3 ]; then
x="1" && z="$(ls -l 01-*.mp3 | wc -l | tr -d ' ')"; for y in 01-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 02-*.mp3 | wc -l | tr -d ' ')"; for y in 02-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
for x in 01-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "01" -D "02" "$x"; done
for x in 02-*.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "02" -D "02" "$x"; done
for x in *.mp3; do y=`echo $x | sed 's/......\(.*\)/\1/' | sed 's/.mp3//g' | sed 's/.mp3//g' | sed 's@_@/@g' | sed 's/¿/?/g'`; eyeD3 --itunes --set-encoding=utf8 -t "$y" "$x"; done
elif [ -f 01\ *.mp3 ]; then
x="1" && z="$(ls -l *.mp3 | wc -l | tr -d ' ')"; for y in *.mp3; do eyeD3 --itunes --set-encoding=utf8 -n "$x" -N "$z" "$y"; x=$[$x+1]; done
for x in *.mp3; do eyeD3 --itunes --set-encoding=utf8 -d "01" -D "01" "$x"; done
for x in *.mp3; do y=`echo $x | sed 's/...\(.*\)/\1/' | sed 's/.mp3//g' | sed 's/.mp3//g' | sed 's@_@/@g' | sed 's/¿/?/g'`; eyeD3 --itunes --set-encoding=utf8 -t "$y" "$x"; done
fi
