#!/bin/bash

# Expected directory structure:
# /Users/username/audio/artist_name/YYYY album_name/NN Track Name.mp3
# Where YYYY is the release year and NN is a two digit track number.

# Deletes id3 tags on all mp3 files in the current directory.
id3v2 -D *.mp3

# Run the script as id3-folder Genre. The genre will be set as that variable.
id3v2 --TCON "$1" *.mp3

# Grabs the artist_name and sets it as the appropriate id3v2 tag.
id3v2 --TPE1 "`pwd | awk -F \/ '{ print $5 }'`" *.mp3

# Grabs the album name (cuts out the release year from the path). Converts _ to / and ¿ to ?.
id3v2 --TALB "`pwd | awk -F \/ '{ print $6 }' | sed 's/.....\(.*\)/\1/' | sed 's@_@/@g' | sed 's/¿/?/g'`" *.mp3

# Cuts the first four characters from the "YYYY album_name" bit of the path for the release year.
id3v2 --TYER "`pwd | awk -F \/ '{ print $6 }' | cut -c 1-4`" *.mp3

# Fun one. Counts the number of tracks in the directory and uses the total tracks and then counts from 1 for the track. 
x="1" && z="`ls -l *.mp3 | wc -l`"; for y in *.mp3; do `id3v2 --TRCK "$x/$z" "$y"`; x=$[$x+1]; done

# Uses the filename (less the .mp3) for the title. Converts _ to / and ¿ to ?.
for x in *.mp3; do y=`echo $x | sed 's/...\(.*\)/\1/' | sed 's/.mp3//g' | sed 's@_@/@g' | sed 's/¿/?/g'`; id3v2 --TIT2 "$y" "$x"; done
