#!/bin/bash
#
# This script expects all artists to be contained within their own directory.
# ie. /home/robot/Music/Artist
#
# Within each folder should be a new directory per album with the release year prepended.
# ie. /home/robot/Music/Artist/1978 Album Title
#
# Each album should contain files prepended with a two digit track number and the title of the track.
# ie. /home/robot/Music/Artist/1978 Album Title/01 First Track.mp3
# An _ will be converted to a / and a ¿ will be converted to ?
#
# In the event of a multi-disc set, the format would be:
# 01-01 First Track of First Disc.mp3
# 02-03 Third Track of Second Disc.mp3
#
# Within each artist folder a file named .genre.txt containing a single line for a genre will be used.
# If no such file is present, then a genre will be requested interactively.
# Alternatively, an argument can be passed to set the genre: $> id3-folder "The Genre"
#
# Deletes id3 tags on all mp3 files in the current directory.
id3v2 -D *.mp3
#
# Run the script as id3-folder Genre. The genre will be set as that variable.
if [ -f ../.genre.txt ] ; then
id3v2 --TCON "$(cat ../.genre.txt)" *.mp3 ; 
else id3v2 --TCON "$@" *.mp3 ;
fi
#
# Uses the artist directory name to set artist name. 
# (See top of file for directory structure notes)
id3v2 --TPE1 "`pwd | awk -F \/ '{ print $(NF-1) }'`" *.mp3
#
# Takes out the year from the album directory and removes the year to set album title.
# (See top of file for directory structure notes)
id3v2 --TALB "`pwd | awk -F \/ '{ print $NF }' | sed 's/.....\(.*\)/\1/' | sed 's@_@/@g' | sed 's/¿/?/g'`" *.mp3
#
# Cuts the first four digits from the album directory for the year.
# Prefers .year.txt if it exists.
if [ -f .year.txt ] ; then
id3v2 --TYER "$(cat .year.txt)" *.mp3 ;
else id3v2 --TYER "`pwd | awk -F \/ '{ print $NF }' | cut -c 1-4`" *.mp3
fi
#
# So, now we figure out how many discs there are and make it assign tracks, number of discs, and track names accordingly.
if [ -f 10-01\ *.mp3 ] ; then
x="1" && z="$(ls -l 01-*.mp3 | wc -l | tr -d ' ')"; for y in 01-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 02-*.mp3 | wc -l | tr -d ' ')"; for y in 02-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 03-*.mp3 | wc -l | tr -d ' ')"; for y in 03-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 04-*.mp3 | wc -l | tr -d ' ')"; for y in 04-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 05-*.mp3 | wc -l | tr -d ' ')"; for y in 05-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 06-*.mp3 | wc -l | tr -d ' ')"; for y in 06-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 07-*.mp3 | wc -l | tr -d ' ')"; for y in 07-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 08-*.mp3 | wc -l | tr -d ' ')"; for y in 08-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 09-*.mp3 | wc -l | tr -d ' ')"; for y in 09-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 10-*.mp3 | wc -l | tr -d ' ')"; for y in 10-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
for x in 01-*.mp3; do id3v2 --TPOS "01/10" "$x"; done
for x in 02-*.mp3; do id3v2 --TPOS "02/10" "$x"; done
for x in 03-*.mp3; do id3v2 --TPOS "03/10" "$x"; done
for x in 04-*.mp3; do id3v2 --TPOS "04/10" "$x"; done
for x in 05-*.mp3; do id3v2 --TPOS "05/10" "$x"; done
for x in 06-*.mp3; do id3v2 --TPOS "06/10" "$x"; done
for x in 07-*.mp3; do id3v2 --TPOS "07/10" "$x"; done
for x in 08-*.mp3; do id3v2 --TPOS "08/10" "$x"; done
for x in 09-*.mp3; do id3v2 --TPOS "09/10" "$x"; done
for x in 10-*.mp3; do id3v2 --TPOS "10/10" "$x"; done
for x in *.mp3; do y=`echo $x | sed 's/......\(.*\)/\1/' | sed 's/.mp3//g' | sed 's/.mp3//g' | sed 's@_@/@g' | sed 's/¿/?/g'`; id3v2 --TIT2 "$y" "$x"; done
elif [ -f 09-01\ *.mp3 ]; then
x="1" && z="$(ls -l 01-*.mp3 | wc -l | tr -d ' ')"; for y in 01-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 02-*.mp3 | wc -l | tr -d ' ')"; for y in 02-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 03-*.mp3 | wc -l | tr -d ' ')"; for y in 03-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 04-*.mp3 | wc -l | tr -d ' ')"; for y in 04-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 05-*.mp3 | wc -l | tr -d ' ')"; for y in 05-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 06-*.mp3 | wc -l | tr -d ' ')"; for y in 06-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 07-*.mp3 | wc -l | tr -d ' ')"; for y in 07-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 08-*.mp3 | wc -l | tr -d ' ')"; for y in 08-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 09-*.mp3 | wc -l | tr -d ' ')"; for y in 09-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
for x in 01-*.mp3; do id3v2 --TPOS "01/09" "$x"; done
for x in 02-*.mp3; do id3v2 --TPOS "02/09" "$x"; done
for x in 03-*.mp3; do id3v2 --TPOS "03/09" "$x"; done
for x in 04-*.mp3; do id3v2 --TPOS "04/09" "$x"; done
for x in 05-*.mp3; do id3v2 --TPOS "05/09" "$x"; done
for x in 06-*.mp3; do id3v2 --TPOS "06/09" "$x"; done
for x in 07-*.mp3; do id3v2 --TPOS "07/09" "$x"; done
for x in 08-*.mp3; do id3v2 --TPOS "08/09" "$x"; done
for x in 09-*.mp3; do id3v2 --TPOS "09/09" "$x"; done
for x in *.mp3; do y=`echo $x | sed 's/......\(.*\)/\1/' | sed 's/.mp3//g' | sed 's/.mp3//g' | sed 's@_@/@g' | sed 's/¿/?/g'`; id3v2 --TIT2 "$y" "$x"; done
elif [ -f 08-01\ *.mp3 ]; then
x="1" && z="$(ls -l 01-*.mp3 | wc -l | tr -d ' ')"; for y in 01-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 02-*.mp3 | wc -l | tr -d ' ')"; for y in 02-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 03-*.mp3 | wc -l | tr -d ' ')"; for y in 03-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 04-*.mp3 | wc -l | tr -d ' ')"; for y in 04-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 05-*.mp3 | wc -l | tr -d ' ')"; for y in 05-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 06-*.mp3 | wc -l | tr -d ' ')"; for y in 06-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 07-*.mp3 | wc -l | tr -d ' ')"; for y in 07-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 08-*.mp3 | wc -l | tr -d ' ')"; for y in 08-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
for x in 01-*.mp3; do id3v2 --TPOS "01/08" "$x"; done
for x in 02-*.mp3; do id3v2 --TPOS "02/08" "$x"; done
for x in 03-*.mp3; do id3v2 --TPOS "03/08" "$x"; done
for x in 04-*.mp3; do id3v2 --TPOS "04/08" "$x"; done
for x in 05-*.mp3; do id3v2 --TPOS "05/08" "$x"; done
for x in 06-*.mp3; do id3v2 --TPOS "06/08" "$x"; done
for x in 07-*.mp3; do id3v2 --TPOS "07/08" "$x"; done
for x in 08-*.mp3; do id3v2 --TPOS "08/08" "$x"; done
for x in *.mp3; do y=`echo $x | sed 's/......\(.*\)/\1/' | sed 's/.mp3//g' | sed 's/.mp3//g' | sed 's@_@/@g' | sed 's/¿/?/g'`; id3v2 --TIT2 "$y" "$x"; done
elif [ -f 07-01\ *.mp3 ]; then
x="1" && z="$(ls -l 01-*.mp3 | wc -l | tr -d ' ')"; for y in 01-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 02-*.mp3 | wc -l | tr -d ' ')"; for y in 02-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 03-*.mp3 | wc -l | tr -d ' ')"; for y in 03-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 04-*.mp3 | wc -l | tr -d ' ')"; for y in 04-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 05-*.mp3 | wc -l | tr -d ' ')"; for y in 05-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 06-*.mp3 | wc -l | tr -d ' ')"; for y in 06-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 07-*.mp3 | wc -l | tr -d ' ')"; for y in 07-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
for x in 01-*.mp3; do id3v2 --TPOS "01/07" "$x"; done
for x in 02-*.mp3; do id3v2 --TPOS "02/07" "$x"; done
for x in 03-*.mp3; do id3v2 --TPOS "03/07" "$x"; done
for x in 04-*.mp3; do id3v2 --TPOS "04/07" "$x"; done
for x in 05-*.mp3; do id3v2 --TPOS "05/07" "$x"; done
for x in 06-*.mp3; do id3v2 --TPOS "06/07" "$x"; done
for x in 07-*.mp3; do id3v2 --TPOS "07/07" "$x"; done
for x in *.mp3; do y=`echo $x | sed 's/......\(.*\)/\1/' | sed 's/.mp3//g' | sed 's/.mp3//g' | sed 's@_@/@g' | sed 's/¿/?/g'`; id3v2 --TIT2 "$y" "$x"; done
elif [ -f 06-01\ *.mp3 ]; then
x="1" && z="$(ls -l 01-*.mp3 | wc -l | tr -d ' ')"; for y in 01-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 02-*.mp3 | wc -l | tr -d ' ')"; for y in 02-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 03-*.mp3 | wc -l | tr -d ' ')"; for y in 03-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 04-*.mp3 | wc -l | tr -d ' ')"; for y in 04-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 05-*.mp3 | wc -l | tr -d ' ')"; for y in 05-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 06-*.mp3 | wc -l | tr -d ' ')"; for y in 06-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
for x in 01-*.mp3; do id3v2 --TPOS "01/06" "$x"; done
for x in 02-*.mp3; do id3v2 --TPOS "02/06" "$x"; done
for x in 03-*.mp3; do id3v2 --TPOS "03/06" "$x"; done
for x in 04-*.mp3; do id3v2 --TPOS "04/06" "$x"; done
for x in 05-*.mp3; do id3v2 --TPOS "05/06" "$x"; done
for x in 06-*.mp3; do id3v2 --TPOS "06/06" "$x"; done
for x in *.mp3; do y=`echo $x | sed 's/......\(.*\)/\1/' | sed 's/.mp3//g' | sed 's/.mp3//g' | sed 's@_@/@g' | sed 's/¿/?/g'`; id3v2 --TIT2 "$y" "$x"; done
elif [ -f 05-01\ *.mp3 ]; then
x="1" && z="$(ls -l 01-*.mp3 | wc -l | tr -d ' ')"; for y in 01-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 02-*.mp3 | wc -l | tr -d ' ')"; for y in 02-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 03-*.mp3 | wc -l | tr -d ' ')"; for y in 03-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 04-*.mp3 | wc -l | tr -d ' ')"; for y in 04-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 05-*.mp3 | wc -l | tr -d ' ')"; for y in 05-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
for x in 01-*.mp3; do id3v2 --TPOS "01/05" "$x"; done
for x in 02-*.mp3; do id3v2 --TPOS "02/05" "$x"; done
for x in 03-*.mp3; do id3v2 --TPOS "03/05" "$x"; done
for x in 04-*.mp3; do id3v2 --TPOS "04/05" "$x"; done
for x in 05-*.mp3; do id3v2 --TPOS "05/05" "$x"; done
for x in *.mp3; do y=`echo $x | sed 's/......\(.*\)/\1/' | sed 's/.mp3//g' | sed 's/.mp3//g' | sed 's@_@/@g' | sed 's/¿/?/g'`; id3v2 --TIT2 "$y" "$x"; done
elif [ -f 04-01\ *.mp3 ]; then
x="1" && z="$(ls -l 01-*.mp3 | wc -l | tr -d ' ')"; for y in 01-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 02-*.mp3 | wc -l | tr -d ' ')"; for y in 02-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 03-*.mp3 | wc -l | tr -d ' ')"; for y in 03-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 04-*.mp3 | wc -l | tr -d ' ')"; for y in 04-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
for x in 01-*.mp3; do id3v2 --TPOS "01/04" "$x"; done
for x in 02-*.mp3; do id3v2 --TPOS "02/04" "$x"; done
for x in 03-*.mp3; do id3v2 --TPOS "03/04" "$x"; done
for x in 04-*.mp3; do id3v2 --TPOS "04/04" "$x"; done
for x in *.mp3; do y=`echo $x | sed 's/......\(.*\)/\1/' | sed 's/.mp3//g' | sed 's/.mp3//g' | sed 's@_@/@g' | sed 's/¿/?/g'`; id3v2 --TIT2 "$y" "$x"; done
elif [ -f 03-01\ *.mp3 ]; then
x="1" && z="$(ls -l 01-*.mp3 | wc -l | tr -d ' ')"; for y in 01-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 02-*.mp3 | wc -l | tr -d ' ')"; for y in 02-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 03-*.mp3 | wc -l | tr -d ' ')"; for y in 03-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
for x in 01-*.mp3; do id3v2 --TPOS "01/03" "$x"; done
for x in 02-*.mp3; do id3v2 --TPOS "02/03" "$x"; done
for x in 03-*.mp3; do id3v2 --TPOS "03/03" "$x"; done
for x in *.mp3; do y=`echo $x | sed 's/......\(.*\)/\1/' | sed 's/.mp3//g' | sed 's/.mp3//g' | sed 's@_@/@g' | sed 's/¿/?/g'`; id3v2 --TIT2 "$y" "$x"; done
elif [ -f 02-01\ *.mp3 ]; then
x="1" && z="$(ls -l 01-*.mp3 | wc -l | tr -d ' ')"; for y in 01-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
x="1" && z="$(ls -l 02-*.mp3 | wc -l | tr -d ' ')"; for y in 02-*.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
for x in 01-*.mp3; do id3v2 --TPOS "01/02" "$x"; done
for x in 02-*.mp3; do id3v2 --TPOS "02/02" "$x"; done
for x in *.mp3; do y=`echo $x | sed 's/......\(.*\)/\1/' | sed 's/.mp3//g' | sed 's/.mp3//g' | sed 's@_@/@g' | sed 's/¿/?/g'`; id3v2 --TIT2 "$y" "$x"; done
elif [ -f 01\ *.mp3 ]; then
x="1" && z="$(ls -l *.mp3 | wc -l | tr -d ' ')"; for y in *.mp3; do id3v2 --TRCK "$x/$z" "$y"; x=$[$x+1]; done
for x in *.mp3; do id3v2 --TPOS "01/01" "$x"; done
for x in *.mp3; do y=`echo $x | sed 's/...\(.*\)/\1/' | sed 's/.mp3//g' | sed 's/.mp3//g' | sed 's@_@/@g' | sed 's/¿/?/g'`; id3v2 --TIT2 "$y" "$x"; done
fi
