#!/bin/bash
#
# Delete all ID3 tags.
id3v2 -D *.mp3
#
echo "Genre:"
read GENRE
id3v2 --TCON "$GENRE" *.mp3
#
echo "Artist:"
read ARTIST
id3v2 --TPE1 "$ARTIST" *.mp3
#
echo "Album Title:"
read ALBUM
id3v2 --TALB "$ALBUM" *.mp3
#
echo "Year:"
read YEAR
id3v2 --TYER "$YEAR" *.mp3
#
# Will name the tracks automagically.
x="1" && z="`ls -l * | wc -l`"; for y in *.mp3; do `id3v2 --TRCK "$x/$z" "$y"`; x=$[$x+1]; done
#
# Will cut the .mp3 off and use the rest for the title.
for x in *.mp3; do y=`echo $x | sed 's/.mp3//g'`; id3v2 --TIT2 "$y" "$x"; done
